[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
solc = "0.8.19"

# Enables to use python scripts in forge tests.
ffi = true

verbosity = 4
optimizers_runs = 200

[fuzz]
max_test_rejects = 1_000_000 # Number of times `vm.assume` can fail

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"